loop_on_end = true

[defaults]
format = "{name} {time}"

[[sessions]]
id = "work"
name = "Work"
duration = "10s"
command = "notify-send -t 999999999 'work session is done'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "8s"
command = "notify-send -t 999999999 'rest session is done'"
