FD_OPTIONS="--hidden --follow --exclude .git --exclude node_modules"

export FZF_CTRL_T_OPTS="
  --preview 'batcat --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
export FZF_DEFAULT_COMMAND="fdfind --type f --type l $FD_OPTIONS"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fdfind --type d $FD_OPTIONS"

# autogenerated completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

_fzf_compgen_path() {
  command fdfind --hidden --follow --exclude .git --exclude node_modules . "$1"
}
_fzf_compgen_dir() {
  command fdfind --type d --hidden --follow --exclude .git --exclude node_modules . "$1"
}
