name: Auto push devcon

# devcon is not yet supports new dotfiles
# on:
#   push:
#     branches:
#       - master

on:
  workflow_dispatch:

jobs:
  dispatch:
    name: Dispatch push workflow
    runs-on: ubuntu-latest

    steps:
      - name: Create workflow dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DEVCON_WORKFLOW_DISPATCH_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'auvred',
              repo: 'devcon',
              workflow_id: 'push-image.yml',
              ref: 'main',
            });
